from typing import IO

from _typeshed import ReadableBuffer

def encode(input: IO[bytes], output: IO[bytes]) -> None: ...
def b64encode(s: ReadableBuffer, altchars: ReadableBuffer | None = None) -> bytes: ...
def b64decode(s: ReadableBuffer, altchars: ReadableBuffer | None = None) -> bytes: ...
