
from _typeshed import ReadableBuffer

def b64encode(s: ReadableBuffer, altchars: ReadableBuffer | None = None) -> bytes: ...
def b64decode(s: ReadableBuffer, altchars: ReadableBuffer | None = None) -> bytes: ...
